services:
  recaptcha-example:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: recaptcha-example:latest
    working_dir: /app
    volumes:
      - .:/app
      # mount an empty folder on /app/node_modules/ so local node_modules will not
      # take the place of container's node_moudles:
      # https://stackoverflow.com/a/37898591
      - /app/node_modules/
    command: pnpm dev -p 3001
    ports:
      - 3001:3001
    container_name: recaptcha-example
    networks:
      - recaptcha-example

networks:
  recaptcha-example:
    driver: bridge
